### ISSUE TITLE
Primitive optionals

### ISSUE THREAD

**Issue by JonMerlevede** [inferred/FreeBuilder#171]
The detection of `Optional` values (as described [in the readme](https://github.com/google/FreeBuilder#optional-values)) does not currently seem to work for primitive values (`OptionalInt`, `OptionalDouble`, ...).

**Comment by masterav10** [comment]
This is of interest to me; I will probably work on this after the solution to #287 .

**Comment by alicederyn** [comment]
FreeBuilder now supports primitive optionals as of [v2.2](https://github.com/inferred/FreeBuilder/releases/tag/v2.2.0). Thanks for the initial report @JonMerlevede, and the initial implementation @masterav10!
