### ISSUE TITLE
array types should emit Arrays.toString() in the toString() method

### ISSUE THREAD

**Issue by chrisrhut** [inferred/FreeBuilder#269]
```java
@FreeBuilder
public interface Test {
  String[] strings();
  
  class Builder extends Test_Builder {
  }
}
```

calling `toString()` on a built `Test` object results in output like:

```
Text{strings=[Ljava.lang.String;@3a1e9209}
```

Array types should be string-ified via `Arrays.toString()`. I'll try to put together a PR for this.

**Comment by chrisalice** [comment]
It's unclear to me how/why mutable types make sense in an immutable value object. What's the use-case that mean you can't use List?

**Comment by chrisalice** [comment]
See also #55.
