### ISSUE TITLE
Add concrete java class support

### ISSUE THREAD

**Issue by artemik** [inferred/FreeBuilder#290]
Now if I want builder I'm forced to use interfaces or abstract classes.

Why should I be limited to this? I may want to use just builder capabilities without following the rest of the guidelines you follow in general.

Also, suppose I already have tons of classes. I'm forced to refactor all that to have interfaces just to start using FreeBuilder to get builder capabilities.

**Comment by chrisalice** [comment]
Do you have a concrete proposal for how that would work?

**Comment by artemik** [comment]
Hey @chrisalice 
I'd expect it to work in the similar way how Lombok or pojobuilder libraries work.
Those allow annotating concrete classes with builder annotation.

**Comment by chrisalice** [comment]
Lombok is not a Java annotation processor and FreeBuilder cannot therefore use the same approach.

Annotating a constructor would mean we could not provide partials, equality, hashcode, internal storage optimizations, or toBuilder methods.
