### ISSUE TITLE
Help needed configuring Gradle/IntelliJ

### ISSUE THREAD

**Issue by pratikpparikh** [inferred/FreeBuilder#291]
Dear Contributor,

Can you add support for JDK9, currently when i add an @FreeBuilder annotation the processor does not produce <ClassName>_Builder code.  

Regards,
Pratik Parikh

**Comment by chrisalice** [comment]
We support and test against Java 9. Can you describe how you are compiling? Are you in an IDE? Using a build tool like Maven?

**Comment by pratikpparikh** [comment]
Thank you for the reply.  I am using IntelliJ for IDE and gradle as build system.  I do see as soon as i plug in the generated_src and respectively generated test directory getting created but nothing happens beyond that when I annotate the interface.

**Comment by chrisalice** [comment]
How are you configuring Gradle? And how are you configuring IntelliJ? Does `gradle compile` generate what you expect?

By default, IntelliJ does not run annotation processors, and even when it does, it will only do it on a recompile.
