### ISSUE TITLE
OptionalDouble/Int/Long not managed as Optional

### ISSUE THREAD

**Issue by lvjp** [inferred/FreeBuilder#304]
The `OptionalDouble/Int/Long` are not fully work like `Optional<Double>` but with native type.

With the input :
```java
@FreeBuilder
public interface MyOptionalData {
  OptionalInt number();
  class Builder extends MyOptionalData_Builder{}
}
```
I didn't have methods like `public Builder number(int){...}` in the created builder like for the `Optional` class.

**Comment by alicederyn** [comment]
Duplicate of #171.

**Comment by alicederyn** [comment]
FreeBuilder now supports primitive optionals as of [v2.2](https://github.com/inferred/FreeBuilder/releases/tag/v2.2.0).
