### ISSUE TITLE
deserializing mongodb document

### ISSUE THREAD

**Issue by thomasricaud** [inferred/FreeBuilder#410]
Hi,

i successfuly wrote a freebuilder java object ( SoftwareComponent ) into my mongodb database using spring-data-mongodb
but i have an issue when trying to access it and deserialize it

`Caused by: org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate com.xxxx.paas.devops.domain.softwarefactory.SoftwareComponent_Builder$Value using constructor private com.xxxx.paas.devops.domain.softwarefactory.SoftwareComponent_Builder$Value(com.xxxx.paas.devops.domain.softwarefactory.SoftwareComponent_Builder) with arguments null
at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:81)`

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.xxxx.paas.devops.domain.softwarefactory.SoftwareComponent_Builder$Value]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:79)`

Do you think i'm trying to do something that is not supported by FreeBuilder or can i fix it by adding some annotation into my class ?

Regards

**Comment by alicederyn** [comment]
Hey, sorry for the delay replying. Unfortunately, as I understand it, Spring only supports beans, not builders, so you won't be able to use FreeBuilder or, generally, the builder pattern with it. However, you should be able to use a Jackson Mongo library instead.
