### ISSUE TITLE
Support remaining Guava collections 

### ISSUE THREAD

**Issue by thespags** [inferred/FreeBuilder#418]
For Maps/Sets/Lists Freebuilder generates nicer builder semantics.

Have you consider similar ones for supporting things like BiMap, Multimap, and others from https://github.com/google/guava/wiki/NewCollectionTypesExplained?

Is this something feasible with detecting if these classes are being used and generate things such as `putBiMap(key, value)`, `putMultimap(key, value) or `putMultimap(key, values...)`.

**Comment by alicederyn** [comment]
[Multiset and multimap are already supported](https://github.com/inferred/FreeBuilder/blob/master/README.md#collections-and-maps), if that is broken for you please do open up a separate issue.

Support for other types like BiMap are definitely possible. FreeBuilder is architected to allow customisation like this for any collection we'd like to add. PRs are welcome.

**Comment by thespags** [comment]
Awesome. I should have looked more closely for multiset and multimap I had hoped you would have done that already.

>PRs are welcome.

Cool, I wanted your blessing for a gave it a whirl. Thanks

**Comment by alicederyn** [comment]
I'm going to mark this as closed with the merging of BiMap, because there are a _lot_ of collections in Guava, and more are added over time, so this is a bit too open-ended. Please do open new issues for any specific collection that you'd like to add!

**Comment by thespags** [comment]
Sounds great. Thanks for the help @alicederyn. Multiset, Multimap, BiMap are the big ones, I'll be the first to let you know when I add one to a freebuilder pojo 😄
