### ISSUE TITLE
Alternative name for build method

### ISSUE THREAD

**Issue by neilswingler** [inferred/FreeBuilder#432]
It could be useful, especially when migrating legacy hand coded builders to Freebuilder, to be able to have the build() method have a different name.

e.g. by declaring the alternative name in the Builder
```java
public Foo buildFoo() {
  return super.buildFoo();
}
```

**Comment by alicederyn** [comment]
Is it necessary to _not_ have the build method present? Otherwise you could just declare the new method in addition:

```
public Foo buildFoo() {
  return super.build();
}
```

**Comment by neilswingler** [comment]
In my  use case I want to overload the build method to return a different type.

I have a mutable data object with getters/setters and a hand coded builder that I hope will eventually be migrated to an immutable Freebuilder implementation but as a stepping stone I want to at least be able to use FreeBuilder for the builder part.

**Comment by alicederyn** [comment]
Can you post a simplified example of what that API would look like?

There are two methods on builders with the same signature (no parameters, returns a Foo), `build` and `buildPartial`, and while I can't think of any others users might want to add, it would be API-breaking to stop emitting `build` if one were added — but depending on the exact pattern you're making, it may still be possible to reliably detect it without breaking other use cases.

**Comment by neilswingler** [comment]
Could this work? It would not be a breaking change because currently, overloading the build() method return type leads to a compiler error. 

```java
@Freebuilder
interface Foo {
    class Builder extends Foo_Builder {
        public Bar build() { ... }  // incompatible return type => don't emit a build()
        public Foo buildFoo() { // compatible return type, emit buildFoo instead
            return super.buildFoo();
        |
    }
}
```

**Comment by alicederyn** [comment]
I would prefer to find a non-obscured method name matching a specific pattern for selecting the build method — perhaps this:

1) If the `build()` method is protected or package-protected on the subclass, follow suit
2) If the `build()` method is private or signature-incompatible, instead generate a package-protected `_buildImpl()` method for the subclass to call
3) _Optional for first implementation_ If that method is already present and incompatible, continue trying with `_buildImpl2()` etc. until a suitable candidate is found

This then cleanly extends to other methods in future, e.g. `buildPartial()` becomes `_buildPartialImpl()`

That would make your code look like:

```java
@FreeBuilder
interface Foo {
    class Builder extends Foo_Builder {
        public Bar build() { ... }  // incompatible return type => FreeBuilder emits _buildImpl instead
        public Foo buildFoo() {
            return super._buildImpl();
        }
    }
}
```

I would be happy to accept a PR implementing this feature. If you are interested in doing this, let me know and I'll point you to the bits of the code you'd need to fit it into.

**Comment by neilswingler** [comment]
Thanks for giving it the consideration Alice. I'm off on holiday now but
hopefully might have some time in September to try to make a pr.

**Comment by alicederyn** [comment]
Gmail doesn't notify me of forum messages, so if you do pick it up, feel free reach out to me directly by email for a quicker response. Meanwhile, enjoy your holiday!

**Comment by alicederyn** [comment]
Hopefully [FreeBuilder v2.7.0](https://github.com/inferred/FreeBuilder/releases/tag/v2.7.0) will solve this issue for you. Please do raise another issue if it does not!

**Comment by neilswingler** [comment]
Thanks a lot. I tried it out already.
