### ISSUE TITLE
Custom getters inside builder

### ISSUE THREAD

**Issue by stijnb1234** [inferred/FreeBuilder#464]
I have a class like this:
```java
public abstract class Vehicle {
  public abstract String getTypeId();
  
  public Type getType() {
    //TODO Call stuff to get the Type
  }

  public abstract Builder toBuilder();
  public static class Builder extends Vehicle_Builder {}
}
```

How can I get the getType() function inside the generated builder too? I won't like to define it twice.

**Comment by alicederyn** [comment]
This is not currently supported. FWIW, I don't think this is the right ownership for this behaviour. The `typeId` to `Type` conversion belongs to the `Type` class; `Vehicle` should just store a `Type` object, and not expose its conversion functions. It's too tightly coupled.

**Comment by stijnb1234** [comment]
Ah right, I see. And I have a List<Part> with a getter and a getter with a class parameter (generics) to get the parts with that class. Sadly I can't create getters with a parameter. How can I do that?

**Comment by alicederyn** [comment]
That's also not supported I'm afraid! I'm not sure how that would work tbh. How would the value depend on the type? Wouldn't it be the other way around?

**Comment by stijnb1234** [comment]
> That's also not supported I'm afraid! I'm not sure how that would work tbh. How would the value depend on the type? Wouldn't it be the other way around? Perhaps you could paste a code snippet of how you would implement it by hand.

```java
abstract class Part {}

class Wheel extends Part {}
class Seat extends Part {}
```

And then:
```java
class Vehicle {
  List<Part> parts;

  public <V> V getPart(@NotNull Class<V> partClass) {
        return parts.stream().filter(partClass::isInstance).map(partClass::cast).findFirst().orElse(null);
  }
}

**Comment by alicederyn** [comment]
That's very bespoke, I can't imagine this being used enough to put into a code generator. It might be a use-case for issue #14 if that ever gets implemented.
