### ISSUE TITLE
error-prone errors on code generated for array properties

### ISSUE THREAD

**Issue by kyegupov** [inferred/FreeBuilder#55]
ACTUAL:

compiling

```
@FreeBuilder
public abstract static class SomeClass {
  public abstract byte[] getBytes();

  static class Builder extends SomeClass_Builder {}
}
```

results in:

```
SomeClass_Builder.java:114: error: [ArrayEquals] Reference equality used to compare arrays
      if (!bytes.equals(other.bytes)) {
```

EXPECTED:
- byte[] supported 
  
  OR 
- a graceful error message during compilation that suggests to use List<Byte>.

**Comment by cjp39** [comment]
That's error-prone, not javac. The generated code is legal, if questionable.

**Comment by cjp39** [comment]
If we add array support, how would you expect it to behave? Copy-on-read?

**Comment by yk4ever** [comment]
I suppose FreeBuilder doesn't copy-on-read other mutable classes? Then I see no good reason to special-case arrays. Let the user cope with mutability.
I suspect byte[] will be the only common use case, and those are rarely mutated anyway.
